depo_homepage:
    path:     /
    defaults: { _controller: DepoBundle:Default:index }

Ingreso:
    resource: "@DepoBundle/Controller/IngresoController.php"
    type:     annotation
    
Cliente:
    resource: "@DepoBundle/Controller/ClienteController.php"
    type:     annotation
    
Producto:
    resource: "@DepoBundle/Controller/ProductoController.php"
    type:     annotation
    
Pedido:
    resource: "@DepoBundle/Controller/PedidoController.php"
    type:     annotation
    
Transporte:
    resource: "@DepoBundle/Controller/TransporteController.php"
    type:     annotation
    
Envio:
    resource: "@DepoBundle/Controller/EnvioController.php"
    type:     annotation
    
Depsoito:
    resource: "@DepoBundle/Controller/DepositoController.php"
    type:     annotation
    
Caja:
    resource: "@DepoBundle/Controller/CajaController.php"
    type:     annotation

CuentaCorriente:
    resource: "@DepoBundle/Controller/CuentaCorrienteController.php"
    type:     annotation