<?php

namespace RS\DepoStock\DepoBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * EnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvioRepository extends EntityRepository
{
    /**
     * Devuelve los envios DESC por fecha
     */
    public function findAllOrdenadosFecha()
    {
        return $this->findBy(array(), array('fecha' => 'DESC'));        
    } 
}
