<?php

namespace RS\DepoStock\DepoBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
    /**
     * Devuelve los pedidos DESC por fecha
     */
    public function findAllOrdenadosFecha()
    {
        return $this->findBy(array(), array('fecha' => 'DESC'));        
    }    
    
}
