<?php

namespace RS\DepoStock\DepoBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoProductoRepository extends EntityRepository
{
}
