<?php

namespace RS\DepoStock\DepoBundle\Entity\Envio;

use Doctrine\ORM\EntityRepository;

/**
 * EnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvioRepository extends EntityRepository
{
}
